### ISSUE TITLE
Conection lost na demopage a schizofrenie presenter/controller

### ISSUE THREAD

**Issue by AdamVyborny** [iPublikuj/demo#1]
Tak jsem z toho nějaký zmatený, na demu zadám nickname sockety vyhoděj connection lost. Další věc je, že projekt na gitu má presenter i controller shodný obsah, který se v komentáři tváří jako presenter, ale classu má jako controller?!

**Comment by akadlec** [comment]
Pkud myslíš funkční demo tak to je pozastaveno. A ke kontroleru a presenteru, který máš na mysli?

**Comment by AdamVyborny** [comment]
WebsocketsPresenter.php a DemoChatController.php

**Comment by akadlec** [comment]
a co mají společného? Jen typo v php docu hlavičky.

**Comment by AdamVyborny** [comment]
Hm, tak se mi to nějak zvláštně stáhlo… Sorry

**Comment by akadlec** [comment]
ok, tedy zavírám
